# This file includes US Core resource examples to load for the Inferno US Core v3.1.1 Test
### REST Client
@contentType = application/json

## For local use
@fhirurl = https://localhost:44348

### Get the bearer token, if authentication is enabled.
# @name getAADToken
POST https://{{fhirurl}}/connect/token
content-type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=globalAdminServicePrincipal
&client_secret=globalAdminServicePrincipal
&scope=fhir-api

## For test server
# @fhirurl=  https://smartonfhir-test1.fhir.azurehealthcareapis.com
# @clientid= b9c9d8e9-8cb7-43ee-91bd-f133f99e9f2c
# @clientsecret= XXX
# @tenantid= 72f988bf-86f1-41af-91ab-2d7cd011db47
#
# ### Get access token
# # @name getAADToken
# POST https://login.microsoftonline.com/{{tenantid}}/oauth2/token
# Content-Type: application/x-www-form-urlencoded
#
# grant_type=client_credentials
# &resource={{fhirurl}}
# &client_id={{clientid}}
# &client_secret={{clientsecret}}

# ### Capture access token from getToken request

@token={{getAADToken.response.body.access_token}}

### Get Metadata - Allows you to get the current capability statement
# this will update as you add profiles to the database
GET {{fhirurl}}/metadata
Authorization: Bearer {{token}}
content-type: {{contentType}}

### Setup test data
POST {{fhirurl}}
Content-Type: application/json
Authorization: Bearer {{token}}

< ./V3.1.1_USCoreCompliantResources.json

### Get
GET {{fhirurl}}/Patient/PatientA
Authorization: Bearer {{token}}
content-type: {{contentType}}

### Delete
DELETE {{fhirurl}}/Organization/OrganizationAcmeLab
Authorization: Bearer {{token}}
content-type: {{contentType}}
