<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>$(NoWarn);NU5104;NU5100;CA1812;CA1515;CA2000</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>$(NoWarn);NU5104;NU5100;CA1812;CA1515;CA2000</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ensure.That" />
    <PackageReference Include="xunit.v3.extensibility.core" />
    <PackageReference Include="xunit.v3.core" />
    <PackageReference Include="xunit.v3.assert" />
  </ItemGroup>

</Project>
