# Configuration based on https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 20
    groups:
      hl7-fhir:
        patterns:
          - "Hl7.Fhir.*"
      azure-sdk:
        patterns:
          - "Azure.*"
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 20
    groups:
      codeql:
        patterns:
          - "github/codeql-action/*"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/build/docker"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 20
    groups:
      dotnet-images:
        patterns:
          - "dotnet/*"
