<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Microsoft.Health.Internal.Fhir.IncludePerf.SqlOps</AssemblyName>
    <RootNamespace>Microsoft.Health.Internal.Fhir.IncludePerf.SqlOps</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Azure.Identity" />
  </ItemGroup>

</Project>
