//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Health.ControlPlane.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Health.ControlPlane.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity provider audience is null..
        /// </summary>
        internal static string IdentityProviderAudienceIsNull {
            get {
                return ResourceManager.GetString("IdentityProviderAudienceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity provider authority is null or empty..
        /// </summary>
        internal static string IdentityProviderAuthorityEmpty {
            get {
                return ResourceManager.GetString("IdentityProviderAuthorityEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Provider Definition Is Invalid..
        /// </summary>
        internal static string IdentityProviderDefinitionIsInvalid {
            get {
                return ResourceManager.GetString("IdentityProviderDefinitionIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of audience values is null or empty..
        /// </summary>
        internal static string IdentityProviderInvalidAudience {
            get {
                return ResourceManager.GetString("IdentityProviderInvalidAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Invalid Authority {0}. Cannot load metadata url {1}&quot;..
        /// </summary>
        internal static string IdentityProviderInvalidMetadataUrl {
            get {
                return ResourceManager.GetString("IdentityProviderInvalidMetadataUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Authority {0}. Required property {1} is missing in metadata from url {2}..
        /// </summary>
        internal static string IdentityProviderMissingMetaProp {
            get {
                return ResourceManager.GetString("IdentityProviderMissingMetaProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity provider name is null or empty..
        /// </summary>
        internal static string IdentityProviderNameEmpty {
            get {
                return ResourceManager.GetString("IdentityProviderNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity provider &apos;{0}&apos; was not found..
        /// </summary>
        internal static string IdentityProviderNotFound {
            get {
                return ResourceManager.GetString("IdentityProviderNotFound", resourceCulture);
            }
        }
    }
}
