//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Health.Fhir.CosmosDb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Health.Fhir.CosmosDb.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get or access the Azure AD token to access the customer-managed key..
        /// </summary>
        internal static string AadClientCredentialsGrantFailure {
            get {
                return ResourceManager.GetString("AadClientCredentialsGrantFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure AD service is unavailable to get access to the customer-managed key..
        /// </summary>
        internal static string AadServiceUnavailable {
            get {
                return ResourceManager.GetString("AadServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-queries in a chained expression cannot return more than {0} results, please use a more selective criteria..
        /// </summary>
        internal static string ChainedExpressionSubqueryLimit {
            get {
                return ResourceManager.GetString("ChainedExpressionSubqueryLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error using the customer-managed key..
        /// </summary>
        internal static string CmkDefaultError {
            get {
                return ResourceManager.GetString("CmkDefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _include:iterate and _revinclude:iterate are not supported..
        /// </summary>
        internal static string IncludeIterateNotSupported {
            get {
                return ResourceManager.GetString("IncludeIterateNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistency level &apos;{0}&apos; specified in the request is invalid when service is configured with consistency level &apos;{1}&apos;. Ensure the request consistency level is not stronger than the service consistency level..
        /// </summary>
        internal static string InvalidConsistencyLevel {
            get {
                return ResourceManager.GetString("InvalidConsistencyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error: the input bytes are not in base64 format..
        /// </summary>
        internal static string InvalidInputBytes {
            get {
                return ResourceManager.GetString("InvalidInputBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer-managed key URI is invalid..
        /// </summary>
        internal static string InvalidKeyVaultKeyUri {
            get {
                return ResourceManager.GetString("InvalidKeyVaultKeyUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Vault does not grant permission to the Azure AD, or the customer-managed key is disabled..
        /// </summary>
        internal static string KeyVaultAuthenticationFailure {
            get {
                return ResourceManager.GetString("KeyVaultAuthenticationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve the DNS name of the Key Vault of the customer-managed key..
        /// </summary>
        internal static string KeyVaultDnsNotResolved {
            get {
                return ResourceManager.GetString("KeyVaultDnsNotResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Vault internal service errors accessing the customer-managed key..
        /// </summary>
        internal static string KeyVaultInternalServerError {
            get {
                return ResourceManager.GetString("KeyVaultInternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer-managed key is not found..
        /// </summary>
        internal static string KeyVaultKeyNotFound {
            get {
                return ResourceManager.GetString("KeyVaultKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Key Vault Service is unavailable to access the customer-managed key..
        /// </summary>
        internal static string KeyVaultServiceUnavailable {
            get {
                return ResourceManager.GetString("KeyVaultServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure to Wrap or Unwrap the customer-managed key..
        /// </summary>
        internal static string KeyVaultWrapUnwrapFailure {
            get {
                return ResourceManager.GetString("KeyVaultWrapUnwrapFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled {0} &apos;{1}&apos;..
        /// </summary>
        internal static string UnhandledEnumValue {
            get {
                return ResourceManager.GetString("UnhandledEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid consistency level &apos;{0}&apos;. Valid values are: {1}..
        /// </summary>
        internal static string UnrecognizedConsistencyLevel {
            get {
                return ResourceManager.GetString("UnrecognizedConsistencyLevel", resourceCulture);
            }
        }

        internal static string InvalidCosmosContinuationTokenSize {
            get {
                return ResourceManager.GetString("InvalidCosmosContinuationTokenSize", resourceCulture);
            }
        }
    }
}
