function New-FhirServerClientApplicationRegistration {
    <#
    .SYNOPSIS
    Create an AAD Application registration for a client application.
    .DESCRIPTION
    Create a new AAD Application registration for a client application that consumes an API.
    .EXAMPLE
    New-FhirServerClientApplicationRegistration -DisplayName "clientapplication" -ApiAppId 9125e524-1509-XXXX-XXXX-74137cc75422
    .PARAMETER ApiAppId
    API AAD Application registration Id
    .PARAMETER DisplayName
    Display name for the client AAD Application registration
    .PARAMETER ReplyUrl
    Reply URL for the client AAD Application registration
    .PARAMETER IdentifierUri
    Identifier URI for the client AAD Application registration
    .PARAMETER PublicClient
    Switch to indicate if the client application should be a public client (desktop/mobile applications)
    #>
    param(
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$ApiAppId,

        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$DisplayName,

        [Parameter(Mandatory = $false)]
        [string]$ReplyUrl = "https://www.getpostman.com/oauth2/callback",

        [Parameter(Mandatory = $false)]
        [string]$IdentifierUri = "api://$DisplayName",

        [Parameter(Mandatory = $false)]
        [switch]$PublicClient
    )

    Set-StrictMode -Version Latest
    
    # Get current Microsoft Graph context
    try {
        $context = Get-MgContext -ErrorAction Stop
        if (-not $context) {
            throw "No Microsoft Graph session found"
        }
    } 
    catch {
        throw "Please log in to Microsoft Graph with Connect-MgGraph cmdlet before proceeding"
    }

    # The API application may have just been created, so it can take a moment to become
    # queryable on Microsoft Graph. Retry the lookup until it propagates before using it.
    $apiAppReg = $null
    for ($attempt = 1; $attempt -le 5; $attempt++) {
        $apiAppReg = Get-MgApplication -Filter "AppId eq '$ApiAppId'" -ErrorAction Stop
        if ($apiAppReg) {
            break
        }

        if ($attempt -eq 5) {
            throw "API application '$ApiAppId' was not found on Microsoft Graph."
        }

        $delaySeconds = 5 * [math]::Pow(2, $attempt - 1)
        Write-Warning "Waiting for API application $ApiAppId to become available before registering the client application (attempt $attempt of 5)."
        Start-Sleep -Seconds $delaySeconds
    }

    # Some GUID values for Azure Active Directory
    # Windows AAD Resource ID:
    $windowsAadResourceId = "00000002-0000-0000-c000-000000000000"
    # 'Sign in and read user profile' permission (scope)
    $signInScope = "311a71cc-e848-46a1-bdf8-97ff7156d8e6"

    # Required App permission for Azure AD sign-in
    $reqAad = @{
        ResourceAppId  = $windowsAadResourceId
        ResourceAccess = @(@{
            Id   = $signInScope
            Type = "Scope"
        })
    }

    # Required App Permission for the API application registration
    $reqApi = @{
        ResourceAppId  = $apiAppReg.AppId
        ResourceAccess = @()
    }
    
    # Only add OAuth2 permission scope if it exists
    if ($apiAppReg.Api -and $apiAppReg.Api.Oauth2PermissionScopes -and $apiAppReg.Api.Oauth2PermissionScopes.Count -gt 0) {
        $reqApi.ResourceAccess = @(@{
            Id   = $apiAppReg.Api.Oauth2PermissionScopes[0].Id
            Type = "Scope"
        })
    }

    $appParams = @{
        DisplayName            = $DisplayName
        RequiredResourceAccess = @($reqAad, $reqApi)
        Web                    = @{
            RedirectUris = @($ReplyUrl)
        }
        # Create the client secret in the same POST /applications request. Microsoft Graph
        # returns the generated secretText only in this create response, so the secret no
        # longer depends on the new application object propagating before a separate
        # Add-MgApplicationPassword call can address it.
        PasswordCredentials    = @(@{
            DisplayName = "Generated by New-FhirServerClientApplicationRegistration"
        })
    }

    if ($PublicClient) {
        $appParams.PublicClient = @{
            RedirectUris = @($ReplyUrl)
        }
        $appParams.IsFallbackPublicClient = $true
    } else {
        $appParams.IdentifierUris = @($IdentifierUri)
    }

    $clientAppReg = New-MgApplication @appParams -ErrorAction Stop

    # Read the generated secret once from the create response. Fail explicitly (without
    # echoing any credential data) rather than returning an application with no usable secret.
    $clientAppSecret = $null
    $createdPasswordCredentials = @($clientAppReg.PasswordCredentials | Where-Object { $null -ne $_ })
    if ($createdPasswordCredentials.Count -gt 0) {
        $clientAppSecret = $createdPasswordCredentials[0].SecretText
    }

    if ([string]::IsNullOrEmpty($clientAppSecret)) {
        throw "Microsoft Graph created client application $($clientAppReg.AppId) but did not return the generated client secret."
    }

    # Create Service Principal
    New-FhirServerServicePrincipal -AppId $clientAppReg.AppId

    $securityAuthenticationAudience = $apiAppReg.IdentifierUris[0]
    $tenantId = $context.TenantId
    $securityAuthenticationAuthority = "https://login.microsoftonline.com/$tenantId"

    @{
        AppId     = $clientAppReg.AppId;
        AppSecret = $clientAppSecret;
        ReplyUrl  = $clientAppReg.Web.RedirectUris[0]
        AuthUrl   = "$securityAuthenticationAuthority/oauth2/authorize?resource=$securityAuthenticationAudience"
        TokenUrl  = "$securityAuthenticationAuthority/oauth2/token"
    }
}
