function New-FhirServerClientApplicationRegistration {
    <#
    .SYNOPSIS
    Create an AAD Application registration for a client application.
    .DESCRIPTION
    Create a new AAD Application registration for a client application that consumes an API.
    .EXAMPLE
    New-FhirServerClientApplicationRegistration -DisplayName "clientapplication" -ApiAppId 9125e524-1509-XXXX-XXXX-74137cc75422
    .PARAMETER ApiAppId
    API AAD Application registration Id
    .PARAMETER DisplayName
    Display name for the client AAD Application registration
    .PARAMETER ReplyUrl
    Reply URL for the client AAD Application registration
    .PARAMETER IdentifierUri
    Identifier URI for the client AAD Application registration
    .PARAMETER PublicClient
    Switch to indicate if the client application should be a public client (desktop/mobile applications)
    #>
    param(
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$ApiAppId,

        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$DisplayName,

        [Parameter(Mandatory = $false)]
        [string]$ReplyUrl = "https://www.getpostman.com/oauth2/callback",

        [Parameter(Mandatory = $false)]
        [string]$IdentifierUri = "api://$DisplayName",

        [Parameter(Mandatory = $false)]
        [switch]$PublicClient
    )

    Set-StrictMode -Version Latest
    
    # Get current Microsoft Graph context
    try {
        $context = Get-MgContext -ErrorAction Stop
        if (-not $context) {
            throw "No Microsoft Graph session found"
        }
    } 
    catch {
        throw "Please log in to Microsoft Graph with Connect-MgGraph cmdlet before proceeding"
    }

    $apiAppReg = Get-MgApplication -Filter "AppId eq '$ApiAppId'"

    # Some GUID values for Azure Active Directory
    # Windows AAD Resource ID:
    $windowsAadResourceId = "00000002-0000-0000-c000-000000000000"
    # 'Sign in and read user profile' permission (scope)
    $signInScope = "311a71cc-e848-46a1-bdf8-97ff7156d8e6"

    # Required App permission for Azure AD sign-in
    $reqAad = @{
        ResourceAppId  = $windowsAadResourceId
        ResourceAccess = @(@{
            Id   = $signInScope
            Type = "Scope"
        })
    }

    # Required App Permission for the API application registration
    $reqApi = @{
        ResourceAppId  = $apiAppReg.AppId
        ResourceAccess = @()
    }
    
    # Only add OAuth2 permission scope if it exists
    if ($apiAppReg.Api -and $apiAppReg.Api.Oauth2PermissionScopes -and $apiAppReg.Api.Oauth2PermissionScopes.Count -gt 0) {
        $reqApi.ResourceAccess = @(@{
            Id   = $apiAppReg.Api.Oauth2PermissionScopes[0].Id
            Type = "Scope"
        })
    }

    $appParams = @{
        DisplayName            = $DisplayName
        RequiredResourceAccess = @($reqAad, $reqApi)
        Web                    = @{
            RedirectUris = @($ReplyUrl)
        }
    }

    if ($PublicClient) {
        $appParams.PublicClient = @{
            RedirectUris = @($ReplyUrl)
        }
        $appParams.IsFallbackPublicClient = $true
    } else {
        $appParams.IdentifierUris = @($IdentifierUri)
    }

    $clientAppReg = New-MgApplication @appParams

    # Create a client secret
    $passwordCredential = @{
        displayName = "Generated by New-FhirServerClientApplicationRegistration"
    }
    $clientAppPassword = Add-MgApplicationPassword -ApplicationId $clientAppReg.Id -PasswordCredential $passwordCredential

    # Create Service Principal
    New-MgServicePrincipal -AppId $clientAppReg.AppId | Out-Null

    $securityAuthenticationAudience = $apiAppReg.IdentifierUris[0]
    $tenantId = $context.TenantId
    $securityAuthenticationAuthority = "https://login.microsoftonline.com/$tenantId"

    @{
        AppId     = $clientAppReg.AppId;
        AppSecret = $clientAppPassword.SecretText;
        ReplyUrl  = $clientAppReg.Web.RedirectUris[0]
        AuthUrl   = "$securityAuthenticationAuthority/oauth2/authorize?resource=$securityAuthenticationAudience"
        TokenUrl  = "$securityAuthenticationAuthority/oauth2/token"
    }
}
