// -------------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// -------------------------------------------------------------------------------------------------

// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "readability", Scope = "member", Target = "~M:Microsoft.Health.Fhir.Store.Copy.Program.RunOsCommand(System.String,System.String,System.Boolean)")]
[assembly: SuppressMessage("Performance", "CA1819:Properties should not return arrays", Justification = "nonsense", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.Resource.RawResource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "readability", Scope = "type", Target = "~T:Microsoft.Health.Fhir.Store.Copy.SqlParamaterResourceExtension")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.Resource.ResourceId")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.Resource.Version")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.Resource.IsHistory")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.Resource.ResourceSurrogateId")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.Resource.IsDeleted")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.Resource.RequestMethod")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.Resource.RawResource")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.Resource.IsRawResourceMetaSet")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.Resource.SearchParamHash")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "readability", Scope = "member", Target = "~M:Microsoft.Health.Fhir.Store.Copy.SqlParamaterResourceExtension.#cctor")]
[assembly: SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "No user input", Scope = "member", Target = "~M:Microsoft.Health.Fhir.Store.Copy.SqlService.GetCorrectedMinResourceSurrogateId(System.Int32,System.String,System.Int16,System.Int64,System.Int64)~System.Int64")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1601:Partial elements should be documented", Justification = "sure", Scope = "type", Target = "~T:Microsoft.Health.Fhir.Store.Copy.SqlService")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "readability", Scope = "type", Target = "~T:Microsoft.Health.Fhir.Store.Copy.SqlParamaterReferenceSearchParamExtension")]
[assembly: SuppressMessage("Design", "CA1056:URI-like properties should not be strings", Justification = "Correct type", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.ReferenceSearchParam.BaseUri")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.ReferenceSearchParam.ResourceSurrogateId")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.ReferenceSearchParam.SearchParamId")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.ReferenceSearchParam.BaseUri")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.ReferenceSearchParam.ReferenceResourceTypeId")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.ReferenceSearchParam.ReferenceResourceId")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.ReferenceSearchParam.ReferenceResourceVersion")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.ReferenceSearchParam.IsHistory")]
[assembly: SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "No user input", Scope = "member", Target = "~M:Microsoft.Health.Fhir.Store.Copy.SqlService.GetData``1(System.Func{System.Data.SqlClient.SqlDataReader,``0},System.Int16,System.Int64,System.Int64)~System.Collections.Generic.IEnumerable{``0}")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.TokenSearchParam.ResourceSurrogateId")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.TokenSearchParam.SearchParamId")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.TokenSearchParam.SystemId")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.TokenSearchParam.Code")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.TokenSearchParam.IsHistory")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "readability", Scope = "type", Target = "~T:Microsoft.Health.Fhir.Store.Copy.SqlParamaterTokenSearchParamExtension")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.CompartmentAssignment.ResourceSurrogateId")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.CompartmentAssignment.CompartmentTypeId")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.CompartmentAssignment.ReferenceResourceId")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "readability", Scope = "member", Target = "~P:Microsoft.Health.Fhir.Store.Copy.CompartmentAssignment.IsHistory")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "readability", Scope = "type", Target = "~T:Microsoft.Health.Fhir.Store.Copy.SqlParamaterCompartmentAssignmentExtension")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "readability", Scope = "type", Target = "~T:Microsoft.Health.Fhir.Store.Copy.SqlParamaterTokenTextExtension")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "readability", Scope = "type", Target = "~T:Microsoft.Health.Fhir.Store.Copy.SqlParamaterDateTimeSearchParamExtension")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "readability", Scope = "type", Target = "~T:Microsoft.Health.Fhir.Store.Copy.SqlParamaterTokenQuantityCompositeSearchParamExtension")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "readability", Scope = "type", Target = "~T:Microsoft.Health.Fhir.Store.Copy.SqlParamaterQuantitySearchParamExtension")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "readability", Scope = "type", Target = "~T:Microsoft.Health.Fhir.Store.Copy.SqlParamaterStringSearchParamExtension")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "readability", Scope = "type", Target = "~T:Microsoft.Health.Fhir.Store.Copy.SqlParamaterTokenTokenCompositeSearchParamExtension")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "readability", Scope = "type", Target = "~T:Microsoft.Health.Fhir.Store.Copy.SqlParamaterTokenStringCompositeSearchParamExtension")]
[assembly: SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "readability", Scope = "member", Target = "~M:Microsoft.Health.Fhir.Store.Copy.SqlService.GetData``1(System.Func{System.Data.SqlClient.SqlDataReader,``0},System.Int16,System.String,System.String)~System.Collections.Generic.IEnumerable{``0}")]
[assembly: SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "No user input", Scope = "member", Target = "~M:Microsoft.Health.Fhir.Store.Copy.SqlService.InsertResources(System.Boolean,System.Collections.Generic.IEnumerable{Microsoft.Health.Fhir.Store.Copy.Resource},System.Collections.Generic.IEnumerable{Microsoft.Health.Fhir.Store.Copy.ReferenceSearchParam},System.Collections.Generic.IEnumerable{Microsoft.Health.Fhir.Store.Copy.TokenSearchParam},System.Collections.Generic.IEnumerable{Microsoft.Health.Fhir.Store.Copy.CompartmentAssignment},System.Collections.Generic.IEnumerable{Microsoft.Health.Fhir.Store.Copy.TokenText},System.Collections.Generic.IEnumerable{Microsoft.Health.Fhir.Store.Copy.DateTimeSearchParam},System.Collections.Generic.IEnumerable{Microsoft.Health.Fhir.Store.Copy.TokenQuantityCompositeSearchParam},System.Collections.Generic.IEnumerable{Microsoft.Health.Fhir.Store.Copy.QuantitySearchParam},System.Collections.Generic.IEnumerable{Microsoft.Health.Fhir.Store.Copy.StringSearchParam},System.Collections.Generic.IEnumerable{Microsoft.Health.Fhir.Store.Copy.TokenTokenCompositeSearchParam},System.Collections.Generic.IEnumerable{Microsoft.Health.Fhir.Store.Copy.TokenStringCompositeSearchParam},System.Boolean)~System.Int32")]
[assembly: SuppressMessage("Security", "CA5394:Do not use insecure randomness", Justification = "not used for security", Scope = "member", Target = "~F:Microsoft.Health.Fhir.Store.Copy.SqlService._partitionId")]
[assembly: SuppressMessage("Security", "CA5394:Do not use insecure randomness", Justification = "not used for security", Scope = "member", Target = "~M:Microsoft.Health.Fhir.Store.Copy.Program.CopyViaBcp(System.Int32,System.Int16,System.Byte,System.Int32,System.Int64,System.Int64)")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1107:Code should not contain multiple statements on one line", Justification = "readability", Scope = "member", Target = "~M:Microsoft.Health.Fhir.Store.Copy.Program.CopyViaSql(System.Boolean,System.Int32,System.Int16,System.Int32,System.String,System.String,System.Boolean)")]
[assembly: SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "No user input", Scope = "member", Target = "~M:Microsoft.Health.Fhir.Store.Copy.SqlService.GetData``1(System.Func{System.Data.SqlClient.SqlDataReader,``0},System.Int16,System.Collections.Generic.IEnumerable{System.String},System.Boolean)~System.Collections.Generic.IEnumerable{``0}")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1107:Code should not contain multiple statements on one line", Justification = "readability", Scope = "member", Target = "~M:Microsoft.Health.Fhir.Store.Copy.Program.CopyViaSqlPartitionByPartOfResourceId(System.Boolean,System.Int16,System.Byte,System.Int32,Azure.Storage.Blobs.BlobContainerClient,System.String,System.Boolean)~System.Int32")]
[assembly: SuppressMessage("Security", "CA5394:Do not use insecure randomness", Justification = "not used for security", Scope = "member", Target = "~M:Microsoft.Health.Fhir.Store.Copy.SqlService.#ctor(System.String,System.String,System.Nullable{System.Byte})")]
