CREATE PROCEDURE dbo.MergeResourcesWithVectorSearchSourceRefresh
    @AffectedRows int = 0 OUT,
    @RaiseExceptionOnConflict bit = 1,
    @IsResourceChangeCaptureEnabled bit = 0,
    @TransactionId bigint = NULL,
    @SingleTransaction bit = 1,
    @Resources dbo.ResourceList READONLY,
    @ResourceWriteClaims dbo.ResourceWriteClaimList READONLY,
    @ReferenceSearchParams dbo.ReferenceSearchParamList READONLY,
    @TokenSearchParams dbo.TokenSearchParamList READONLY,
    @TokenTexts dbo.TokenTextList READONLY,
    @StringSearchParams dbo.StringSearchParamList READONLY,
    @UriSearchParams dbo.UriSearchParamList READONLY,
    @NumberSearchParams dbo.NumberSearchParamList READONLY,
    @QuantitySearchParams dbo.QuantitySearchParamList READONLY,
    @DateTimeSearchParms dbo.DateTimeSearchParamList READONLY,
    @VectorSearchParams dbo.VectorSearchParamList READONLY,
    @ReferenceTokenCompositeSearchParams dbo.ReferenceTokenCompositeSearchParamList READONLY,
    @TokenTokenCompositeSearchParams dbo.TokenTokenCompositeSearchParamList READONLY,
    @TokenDateTimeCompositeSearchParams dbo.TokenDateTimeCompositeSearchParamList READONLY,
    @TokenQuantityCompositeSearchParams dbo.TokenQuantityCompositeSearchParamList READONLY,
    @TokenStringCompositeSearchParams dbo.TokenStringCompositeSearchParamList READONLY,
    @TokenNumberNumberCompositeSearchParams dbo.TokenNumberNumberCompositeSearchParamList READONLY
AS
SET NOCOUNT ON
EXECUTE dbo.MergeResources
    @AffectedRows = @AffectedRows OUT,
    @RaiseExceptionOnConflict = @RaiseExceptionOnConflict,
    @IsResourceChangeCaptureEnabled = @IsResourceChangeCaptureEnabled,
    @TransactionId = @TransactionId,
    @SingleTransaction = @SingleTransaction,
    @EnqueueVectorSearchSourceRefresh = 1,
    @Resources = @Resources,
    @ResourceWriteClaims = @ResourceWriteClaims,
    @ReferenceSearchParams = @ReferenceSearchParams,
    @TokenSearchParams = @TokenSearchParams,
    @TokenTexts = @TokenTexts,
    @StringSearchParams = @StringSearchParams,
    @UriSearchParams = @UriSearchParams,
    @NumberSearchParams = @NumberSearchParams,
    @QuantitySearchParams = @QuantitySearchParams,
    @DateTimeSearchParms = @DateTimeSearchParms,
    @VectorSearchParams = @VectorSearchParams,
    @ReferenceTokenCompositeSearchParams = @ReferenceTokenCompositeSearchParams,
    @TokenTokenCompositeSearchParams = @TokenTokenCompositeSearchParams,
    @TokenDateTimeCompositeSearchParams = @TokenDateTimeCompositeSearchParams,
    @TokenQuantityCompositeSearchParams = @TokenQuantityCompositeSearchParams,
    @TokenStringCompositeSearchParams = @TokenStringCompositeSearchParams,
    @TokenNumberNumberCompositeSearchParams = @TokenNumberNumberCompositeSearchParams
GO
