// -------------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// -------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Logging;

namespace Microsoft.Health.Fhir.SqlServer.Features.Storage
{
    public static class SqlCommandExtensions
    {
        public static async Task ExecuteNonQueryAsync(this SqlCommand cmd, ISqlRetryService retryService, ILogger logger, CancellationToken cancellationToken, string logMessage = null, bool isReadOnly = false, bool disableRetries = false, string applicationName = null)
        {
            await retryService.ExecuteSql(cmd, async (sql, cancel) => await sql.ExecuteNonQueryAsync(cancel), logger, logMessage, cancellationToken, isReadOnly, disableRetries, applicationName);
        }

        public static async Task<IReadOnlyList<TResult>> ExecuteReaderAsync<TResult>(this SqlCommand cmd, ISqlRetryService retryService, Func<SqlDataReader, TResult> readerToResult, ILogger logger, CancellationToken cancellationToken, string logMessage = null, bool isReadOnly = false)
        {
            return await retryService.ExecuteReaderAsync(cmd, readerToResult, logger, logMessage, cancellationToken, isReadOnly);
        }

        /// <summary>
        /// Handles SQL commands that return multiple sets of results. The number of result readers needs to match the number of result sets.
        /// </summary>
        /// <typeparam name="TResult">The type of data returned from the queries</typeparam>
        /// <param name="cmd">The SQL command</param>
        /// <param name="retryService">The SQL retry service</param>
        /// <param name="readersToResult">A list of functions to convert each result set to a list of objects</param>
        /// <param name="logger">The logger</param>
        /// <param name="cancellationToken">The cancellation token</param>
        /// <param name="logMessage">A message to be prepended to the logs generated by this call</param>
        /// <param name="isReadOnly">Can the query be run on a read only replica</param>
        /// <returns>A list of lists containing the parsed results from each result set</returns>
        public static async Task<IReadOnlyList<IReadOnlyList<TResult>>> ExecuteMultiResultReaderAsync<TResult>(this SqlCommand cmd, ISqlRetryService retryService, IList<Func<SqlDataReader, TResult>> readersToResult, ILogger logger, CancellationToken cancellationToken, string logMessage = null, bool isReadOnly = false)
        {
            return await retryService.ExecuteMultiResultReaderAsync(cmd, readersToResult, logger, logMessage, cancellationToken, isReadOnly);
        }

        public static async Task<object> ExecuteScalarAsync(this SqlCommand cmd, ISqlRetryService retryService, ILogger logger, CancellationToken cancellationToken, string logMessage = null, bool isReadOnly = false, bool disableRetries = false)
        {
            object scalar = null;
            await retryService.ExecuteSql(cmd, async (sql, cancel) => { scalar = await sql.ExecuteScalarAsync(cancel); }, logger, logMessage, cancellationToken, isReadOnly, disableRetries);
            return scalar;
        }

        public static async Task<T> ExecuteScalarAsync<T>(this SqlCommand cmd, ISqlRetryService retryService, ILogger logger, CancellationToken cancellationToken, string logMessage = null, bool isReadOnly = false, bool disableRetries = false)
        {
            return (T)await cmd.ExecuteScalarAsync(retryService, logger, cancellationToken, logMessage, isReadOnly, disableRetries);
        }
    }
}
