//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Health.Fhir.Api {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Microsoft.Health.Fhir.Api.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string BackToTop {
            get {
                return ResourceManager.GetString("BackToTop", resourceCulture);
            }
        }
        
        public static string BundleNotFound {
            get {
                return ResourceManager.GetString("BundleNotFound", resourceCulture);
            }
        }
        
        public static string ContentTypeHeaderRequired {
            get {
                return ResourceManager.GetString("ContentTypeHeaderRequired", resourceCulture);
            }
        }
        
        public static string CustomAuditHeaderTooLarge {
            get {
                return ResourceManager.GetString("CustomAuditHeaderTooLarge", resourceCulture);
            }
        }
        
        public static string FailedHealthCheckMessage {
            get {
                return ResourceManager.GetString("FailedHealthCheckMessage", resourceCulture);
            }
        }
        
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        public static string GeneralInternalError {
            get {
                return ResourceManager.GetString("GeneralInternalError", resourceCulture);
            }
        }
        
        public static string GeneralTransactionFailedError {
            get {
                return ResourceManager.GetString("GeneralTransactionFailedError", resourceCulture);
            }
        }
        
        public static string InvalidBundleType {
            get {
                return ResourceManager.GetString("InvalidBundleType", resourceCulture);
            }
        }
        
        public static string InvalidCompoundCode {
            get {
                return ResourceManager.GetString("InvalidCompoundCode", resourceCulture);
            }
        }
        
        public static string InvalidLaunchContext {
            get {
                return ResourceManager.GetString("InvalidLaunchContext", resourceCulture);
            }
        }
        
        public static string InvalidPrettyParameter {
            get {
                return ResourceManager.GetString("InvalidPrettyParameter", resourceCulture);
            }
        }
        
        public static string InvalidRedirectUri {
            get {
                return ResourceManager.GetString("InvalidRedirectUri", resourceCulture);
            }
        }
        
        public static string MenuAPI {
            get {
                return ResourceManager.GetString("MenuAPI", resourceCulture);
            }
        }
        
        public static string MenuCapabilityStatement {
            get {
                return ResourceManager.GetString("MenuCapabilityStatement", resourceCulture);
            }
        }
        
        public static string MissingAuditInformation {
            get {
                return ResourceManager.GetString("MissingAuditInformation", resourceCulture);
            }
        }
        
        public static string NotFoundException {
            get {
                return ResourceManager.GetString("NotFoundException", resourceCulture);
            }
        }
        
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        public static string OperationNotImplemented {
            get {
                return ResourceManager.GetString("OperationNotImplemented", resourceCulture);
            }
        }
        
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        public static string PatchNotSupported {
            get {
                return ResourceManager.GetString("PatchNotSupported", resourceCulture);
            }
        }
        
        public static string RequireHttpsMetadataError {
            get {
                return ResourceManager.GetString("RequireHttpsMetadataError", resourceCulture);
            }
        }
        
        public static string ResourceAndIdRequired {
            get {
                return ResourceManager.GetString("ResourceAndIdRequired", resourceCulture);
            }
        }
        
        public static string ResourceIdRequired {
            get {
                return ResourceManager.GetString("ResourceIdRequired", resourceCulture);
            }
        }
        
        public static string ResourcesMustBeUnique {
            get {
                return ResourceManager.GetString("ResourcesMustBeUnique", resourceCulture);
            }
        }
        
        public static string ResourceTypeMismatch {
            get {
                return ResourceManager.GetString("ResourceTypeMismatch", resourceCulture);
            }
        }
        
        public static string ToggleNavigation {
            get {
                return ResourceManager.GetString("ToggleNavigation", resourceCulture);
            }
        }
        
        public static string TooManyCustomAuditHeaders {
            get {
                return ResourceManager.GetString("TooManyCustomAuditHeaders", resourceCulture);
            }
        }
        
        public static string TransactionFailed {
            get {
                return ResourceManager.GetString("TransactionFailed", resourceCulture);
            }
        }
        
        public static string UnableToObtainOpenIdConfiguration {
            get {
                return ResourceManager.GetString("UnableToObtainOpenIdConfiguration", resourceCulture);
            }
        }
        
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        public static string UnsupportedFormatParameter {
            get {
                return ResourceManager.GetString("UnsupportedFormatParameter", resourceCulture);
            }
        }
        
        public static string UnsupportedHeaderValue {
            get {
                return ResourceManager.GetString("UnsupportedHeaderValue", resourceCulture);
            }
        }
        
        public static string OperationNotEnabled {
            get {
                return ResourceManager.GetString("OperationNotEnabled", resourceCulture);
            }
        }
        
        public static string UnsupportedParameter {
            get {
                return ResourceManager.GetString("UnsupportedParameter", resourceCulture);
            }
        }
        
        public static string UnsupportedResourceType {
            get {
                return ResourceManager.GetString("UnsupportedResourceType", resourceCulture);
            }
        }
        
        public static string UrlResourceIdMismatch {
            get {
                return ResourceManager.GetString("UrlResourceIdMismatch", resourceCulture);
            }
        }
        
        public static string ValueCannotBeNull {
            get {
                return ResourceManager.GetString("ValueCannotBeNull", resourceCulture);
            }
        }
        
        public static string ViewNotFound {
            get {
                return ResourceManager.GetString("ViewNotFound", resourceCulture);
            }
        }
        
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        public static string InvalidBundleEntry {
            get {
                return ResourceManager.GetString("InvalidBundleEntry", resourceCulture);
            }
        }
        
        public static string InvalidConditionalReference {
            get {
                return ResourceManager.GetString("InvalidConditionalReference", resourceCulture);
            }
        }
        
        public static string InvalidConditionalReferenceParameters {
            get {
                return ResourceManager.GetString("InvalidConditionalReferenceParameters", resourceCulture);
            }
        }
        
        public static string ConditionalOperationInBundleNotSelectiveEnough {
            get {
                return ResourceManager.GetString("ConditionalOperationInBundleNotSelectiveEnough", resourceCulture);
            }
        }
        
        public static string ResourceNotSupported {
            get {
                return ResourceManager.GetString("ResourceNotSupported", resourceCulture);
            }
        }
        
        public static string ValidationNotSupported {
            get {
                return ResourceManager.GetString("ValidationNotSupported", resourceCulture);
            }
        }
        
        public static string ValidateWithProfileNotSupported {
            get {
                return ResourceManager.GetString("ValidateWithProfileNotSupported", resourceCulture);
            }
        }
        
        public static string BundleEntryLimitExceeded {
            get {
                return ResourceManager.GetString("BundleEntryLimitExceeded", resourceCulture);
            }
        }
        
        public static string ParsingError {
            get {
                return ResourceManager.GetString("ParsingError", resourceCulture);
            }
        }
        
        public static string ValidationForUpdateAndDeleteNotSupported {
            get {
                return ResourceManager.GetString("ValidationForUpdateAndDeleteNotSupported", resourceCulture);
            }
        }
        
        public static string MultipleModesProvided {
            get {
                return ResourceManager.GetString("MultipleModesProvided", resourceCulture);
            }
        }
        
        public static string MultipleProfilesProvided {
            get {
                return ResourceManager.GetString("MultipleProfilesProvided", resourceCulture);
            }
        }
        
        public static string ValidationModeNotRecognized {
            get {
                return ResourceManager.GetString("ValidationModeNotRecognized", resourceCulture);
            }
        }
        
        public static string ValidationModeNotSupported {
            get {
                return ResourceManager.GetString("ValidationModeNotSupported", resourceCulture);
            }
        }
        
        public static string ReindexParameterNotValid {
            get {
                return ResourceManager.GetString("ReindexParameterNotValid", resourceCulture);
            }
        }
        
        public static string ReindexParametersNotValid {
            get {
                return ResourceManager.GetString("ReindexParametersNotValid", resourceCulture);
            }
        }
        
        public static string TooManyConcurrentRequests {
            get {
                return ResourceManager.GetString("TooManyConcurrentRequests", resourceCulture);
            }
        }
        
        public static string InvalidOutputFormat {
            get {
                return ResourceManager.GetString("InvalidOutputFormat", resourceCulture);
            }
        }
        
        public static string ContainerIsRequiredForAnonymizedExport {
            get {
                return ResourceManager.GetString("ContainerIsRequiredForAnonymizedExport", resourceCulture);
            }
        }
    }
}
