// -------------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// -------------------------------------------------------------------------------------------------

using System.Diagnostics.CodeAnalysis;

// [assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1208:System using directives should be placed before other using directives", Justification = "<TODO>")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File should have header", Justification = "<TODO>")]

// [assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1400:Access modifier should be declared", Justification = "<TODO>", Scope = "module")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name should match first type name", Justification = "<TODO>", Scope = "module")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1307:Accessible fields should begin with upper-case letter", Justification = "<TODO>", Scope = "module")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:Element should begin with upper-case letter", Justification = "<TODO>", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA2201:Do not raise reserved exception types", Justification = "<TODO>", Scope = "module")]

// [assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1503:Braces should not be omitted", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1513:Closing brace should be followed by blank line", Justification = "<TODO>", Scope = "module")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "<TODO>", Scope = "module")]

// [assembly: SuppressMessage("Performance", "CA1819:Properties should not return arrays", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1502:Element should not be on a single line", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1005:Single line comments should begin with single space", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1129:Do not use default value type constructor", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1002:Semicolons should be spaced correctly", Justification = "<PenTODOding>", Scope = "module")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "<TODO>", Scope = "module")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<TODO>", Scope = "module")]

// [assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1008:Opening parenthesis should be spaced correctly", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1206:Declaration keywords should follow order", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1009:Closing parenthesis should be spaced correctly", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1303:Const field names should begin with upper-case letter", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1028:Code should not contain trailing whitespace", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1119:Statement should not use unnecessary parenthesis", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1025:Code should not contain multiple whitespace in a row", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1515:Single-line comment should be preceded by blank line", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1508:Closing braces should not be preceded by blank line", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1505:Opening braces should not be followed by blank line", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1501:Statement should not be on a single line", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1314:Type parameter names should begin with T", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1313:Parameter names should begin with lower-case letter", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1128:Put constructor initializers on their own line", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1127:Generic type constraints should be on their own line", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1122:Use string.Empty for empty strings", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1121:Use built-in type alias", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1117:Parameters should be on same line or separate lines", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1107:Code should not contain multiple statements on one line", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("Design", "CA1056:URI-like properties should not be strings", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("Design", "CA1064:Exceptions should be public", Justification = "<TODO>", Scope = "module")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<TODO>", Scope = "module")]

// [assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("Style", "IDE0007:Use implicit type", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("Performance", "CA1805:Do not initialize unnecessarily", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("Globalization", "CA1310:Specify StringComparison for correctness", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("Style", "IDE0057:Use range operator", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1003:Symbols should be spaced correctly", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1024:Colons Should Be Spaced Correctly", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("Style", "IDE0034:Simplify 'default' expression", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("Style", "IDE0005:Using directive is unnecessary.", Justification = "<TODO>")]
// [assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("Usage", "CA1816:Dispose methods should call SuppressFinalize", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("Design", "CA1032:Implement standard exception constructors", Justification = "<TODO>", Scope = "module")]

// [assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("Style", "IDE0049:Simplify Names", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<TODO>", Scope = "module")]
[assembly: SuppressMessage("Design", "CA1724:NAME CONFLICT", Justification = "<TODO>", Scope = "module")]

// [assembly: SuppressMessage("Design", "CA1812:JSON SERIALIZER INSTANTIATION", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1000:Keywords should be spaced correctly", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private modules", Justification = "<TODO>", Scope = "module")]

// [assembly: SuppressMessage("Usage", "CA2234:Pass system uri objects instead of strings", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("Performance", "CA1806:Do not ignore method results", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<TODO>", Scope = "module")]
// [assembly: SuppressMessage("Style", "IDE0004:Remove Unnecessary Cast", Justification = "<TODO>", Scope = "module")]
