@startuml SearchIndexer
SearchIndexer -> SearchParameterDefinitionManagerResolver : GetSearchParameters
SearchParameterDefinitionManagerResolver -> SearchIndexer : IEnumerable<SearchParameterInfo>
SearchIndexer -> ProcessNonCompositeSearchParameter : SearchParameter
ProcessNonCompositeSearchParameter -> ExtractSearchValues
ExtractSearchValues -> FhirElementToSearchValueTypeConverterManager : TryGetConverter
FhirElementToSearchValueTypeConverterManager -> ExtractSearchValues : IFhirElementToSearchValueTypeConverter
ExtractSearchValues -> IFhirElementToSearchValueTypeConverter : Convert
IFhirElementToSearchValueTypeConverter -> ExtractSearchValues : IEnumerable<ISearchValue>
ExtractSearchValues -> ProcessNonCompositeSearchParameter : IEnumerable<SearchValue>
SearchIndexer -> ProcessCompositeSearchParameter : SearchParameter
ProcessCompositeSearchParameter -> SearchParameterDefinitionManagerResolver :  GetSearchParameter for component
SearchParameterDefinitionManagerResolver -> ProcessCompositeSearchParameter : SearchParameterInfo
ProcessCompositeSearchParameter -> ExtractSearchValues
ExtractSearchValues -> FhirElementToSearchValueTypeConverterManager : TryGetConverter
FhirElementToSearchValueTypeConverterManager -> ExtractSearchValues : IFhirElementToSearchValueTypeConverter
ExtractSearchValues -> IFhirElementToSearchValueTypeConverter : Convert
IFhirElementToSearchValueTypeConverter -> ExtractSearchValues : IEnumerable<ISearchValue>
ExtractSearchValues -> ProcessCompositeSearchParameter : IEnumerable<SearchValue>
ProcessNonCompositeSearchParameter -> SearchIndexer
ProcessCompositeSearchParameter -> SearchIndexer
@enduml