// -------------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// -------------------------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Reflection;
using Microsoft.Data.SqlClient;

namespace Microsoft.Health.Fhir.SqlServer.UnitTests
{
    internal static class SqlExceptionUtils
    {
        private const string ReflectionErrorMessage =
            "Failed to create SqlException via reflection. This may indicate a breaking change in " +
            "Microsoft.Data.SqlClient. Check the internal constructor signatures of SqlException, " +
            "SqlErrorCollection, and SqlError classes.";

        /// <summary>
        /// Creates an SqlException with specific error number.
        /// This is required as SQLException has no public constructor and cannot be mocked easily.
        /// Useful for testing system errors that can't be generated by a user query.
        /// </summary>
        /// <param name="number">Sql exception number</param>
        /// <returns>sql exception</returns>
        public static SqlException CreateSqlException(int number)
        {
            // Create SqlError using reflection
            var error = Create<SqlError>(
                number,      // infoNumber
                (byte)0,     // errorState
                (byte)0,     // errorClass
                string.Empty, // server
                string.Empty, // message
                string.Empty, // procedure
                0,           // lineNumber
                null);       // exception

            // Create SqlErrorCollection using reflection
            var errorCollection = Create<SqlErrorCollection>();

            // Add the error to the collection
            typeof(SqlErrorCollection)
                .GetMethod("Add", BindingFlags.NonPublic | BindingFlags.Instance)
                ?.Invoke(errorCollection, new object[] { error });

            // Create SqlException using the CreateException static method
            var exception = typeof(SqlException)
                .GetMethod(
                    "CreateException",
                    BindingFlags.NonPublic | BindingFlags.Static,
                    null,
                    CallingConventions.ExplicitThis,
                    new[] { typeof(SqlErrorCollection), typeof(string) },
                    new ParameterModifier[] { })
                ?.Invoke(null, new object[] { errorCollection, "7.0.0" }) as SqlException;

            return exception ?? throw new InvalidOperationException("Could not create SqlException");
        }

        /// <summary>
        /// Creates a SqlException with the specified message and inner exception.
        /// </summary>
        /// <param name="message">The exception message.</param>
        /// <param name="innerException">The inner exception.</param>
        /// <returns>A SqlException instance for testing.</returns>
        /// <exception cref="InvalidOperationException">Thrown when reflection fails due to internal API changes.</exception>
        public static SqlException CreateSqlException(string message, Exception innerException)
        {
            var errorCollection = Activator.CreateInstance(
                typeof(SqlErrorCollection),
                nonPublic: true) as SqlErrorCollection
                ?? throw new InvalidOperationException($"{ReflectionErrorMessage} SqlErrorCollection constructor not found.");

            var sqlException = Activator.CreateInstance(
                typeof(SqlException),
                BindingFlags.NonPublic | BindingFlags.Instance,
                binder: null,
                args: new object[] { message, errorCollection, innerException, Guid.NewGuid() },
                culture: null) as SqlException
                ?? throw new InvalidOperationException($"{ReflectionErrorMessage} SqlException constructor not found.");

            return sqlException;
        }

        private static T Create<T>(params object[] parameters)
        {
            var constructors = typeof(T).GetConstructors(BindingFlags.NonPublic | BindingFlags.Instance);
            var constructor = constructors.FirstOrDefault(ctor => ctor.GetParameters().Length == parameters.Length);

            if (constructor == null)
            {
                throw new InvalidOperationException($"Could not find constructor for {typeof(T).Name} with {parameters.Length} parameters");
            }

            return (T)constructor.Invoke(parameters);
        }
    }
}
