version: '3'

services:
  cosmos:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    mem_limit: 3g
    cpu_count: 2
    environment:
        AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 2
        AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: "true"
    volumes:
        - /var/run/docker.sock:/var/run/docker-host.sock
  
  fhir:
    depends_on:
      - "cosmos"
    build: 
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock 
      - ..:/workspace:cached

    entrypoint: /usr/local/share/docker-init.sh

    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    network_mode: service:cosmos

    # so the container won't exit
    command: sleep infinity