<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Microsoft.Health.Fhir.FirelySdk</RootNamespace>
  </PropertyGroup>
  <PropertyGroup>
    <DefineConstants>R4</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Microsoft.Health.Fhir.FirelySdk\Features\Operations\Import\FirelyImportResourceParser.cs" Link="Features\Operations\Import\FirelyImportResourceParser.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ensure.That" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.Health.Fhir.R4.Core\Microsoft.Health.Fhir.R4.Core.csproj" />
  </ItemGroup>
</Project>
