version: '3.8'

services:
  fhir:
    build: 
      context: ../../
      dockerfile: .devcontainer/Dockerfile
      args:
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock 
      - ../../:/workspace:cached
      # Cache for better performance
      - fhir-local-node-modules:/workspace/node_modules
      - fhir-local-obj:/workspace/obj
      - fhir-local-bin:/workspace/bin

    entrypoint: /usr/local/share/docker-init.sh

    # Use host networking to easily access host database services
    network_mode: "host"
    
    environment:
      # FHIR Server configuration - uses host database instances
      DataStore: "${DATASTORE_TYPE:-SqlServer}"
      # SQL Server configuration (connects to host instance)
      SqlServer__AllowDatabaseCreation: "true"
      SqlServer__Initialize: "true"  
      SqlServer__SchemaOptions__AutomaticUpdatesEnabled: "true"
      SqlServer__ConnectionString: "${SQL_SERVER_CONNECTION:-server=host.docker.internal;Initial Catalog=FHIR;Integrated Security=true;TrustServerCertificate=true}"
      # Cosmos DB configuration (connects to host instance or emulator)
      CosmosDb__Host: "${COSMOS_DB_HOST:-https://host.docker.internal:8081}"
      CosmosDb__Key: "${COSMOS_DB_KEY:-C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==}"
      CosmosDb__DatabaseId: "FhirDev"
      CosmosDb__AllowDatabaseCreation: "true"
      CosmosDb__AllowCollectionSetup: "true"
      CosmosDb__UseManagedIdentity: "false"
      # Common settings
      TestAuthEnvironment__FilePath: "/workspace/testauthenvironment.json"
      ASPNETCORE_ENVIRONMENT: "Development"
      TaskHosting__Enabled: "true"
      TaskHosting__MaxRunningTaskCount: "2"
      # Enable authentication for local development (more realistic)
      FhirServer__Security__Enabled: "true"
      # Storage settings - can be overridden for real Azure storage
      FhirServer__Operations__Export__StorageAccountConnection: "${EXPORT_STORAGE_CONNECTION:-UseDevelopmentStorage=true}"
      FhirServer__Operations__IntegrationDataStore__StorageAccountConnection: "${INTEGRATION_STORAGE_CONNECTION:-UseDevelopmentStorage=true}"
      FhirServer__Operations__Import__Enabled: "true"
      # Additional local development settings
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_FALLBACK_PACKAGES: "/workspace/.nuget/fallbackpackages"
    
    # so the container won't exit
    command: sleep infinity

volumes:
  fhir-local-node-modules:
  fhir-local-obj:
  fhir-local-bin: