//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Health.Fhir.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Health.Fhir.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1} cannot both be specified..
        /// </summary>
        internal static string AtCannotBeSpecifiedWithBeforeOrSince {
            get {
                return ResourceManager.GetString("AtCannotBeSpecifiedWithBeforeOrSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only a bundle can be submitted for batch or transaction processing..
        /// </summary>
        internal static string BundleRequiredForBatchOrTransaction {
            get {
                return ResourceManager.GetString("BundleRequiredForBatchOrTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find &apos;{0}&apos; in type &apos;{1}&apos;.
        /// </summary>
        internal static string CantResolveExpressionForAType {
            get {
                return ResourceManager.GetString("CantResolveExpressionForAType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} Capability Statement.
        /// </summary>
        internal static string CapabilityStatementNameFormat {
            get {
                return ResourceManager.GetString("CapabilityStatementNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chained parameter must be a reference search parameter type..
        /// </summary>
        internal static string ChainedParameterMustBeReferenceSearchParamType {
            get {
                return ResourceManager.GetString("ChainedParameterMustBeReferenceSearchParamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chained parameter is not supported..
        /// </summary>
        internal static string ChainedParameterNotSupported {
            get {
                return ResourceManager.GetString("ChainedParameterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference search parameter &apos;{0}&apos; refers to multiple possible resource types. Please specify a type in the search expression: {1}.
        /// </summary>
        internal static string ChainedParameterSpecifyType {
            get {
                return ResourceManager.GetString("ChainedParameterSpecifyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The (rev)chained resource type is not allowed.  Additional clinical scopes must be requested to allow searches using the chained type..
        /// </summary>
        internal static string ChainedResourceTypesNotAllowedDueToScope {
            get {
                return ResourceManager.GetString("ChainedResourceTypesNotAllowedDueToScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to search parameters is not allowed while a reindex job is ongoing.  Wait for the reindex job with Id: {0} to finish, or cancel it..
        /// </summary>
        internal static string ChangesToSearchParametersNotAllowedWhileReindexing {
            get {
                return ResourceManager.GetString("ChangesToSearchParametersNotAllowedWhileReindexing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparator &apos;{0}&apos; is not supported for search parameter &apos;{1}&apos;..
        /// </summary>
        internal static string ComparatorNotSupported {
            get {
                return ResourceManager.GetString("ComparatorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compartment definition contains one or more invalid entries..
        /// </summary>
        internal static string CompartmentDefinitionContainsInvalidEntry {
            get {
                return ResourceManager.GetString("CompartmentDefinitionContainsInvalidEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bundle.entry[{0}].resource has duplicate resources..
        /// </summary>
        internal static string CompartmentDefinitionDupeResource {
            get {
                return ResourceManager.GetString("CompartmentDefinitionDupeResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bundle.entry[{0}] is null..
        /// </summary>
        internal static string CompartmentDefinitionInvalidBundle {
            get {
                return ResourceManager.GetString("CompartmentDefinitionInvalidBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bundle.entry[{0}].resource.code is null. Not a valid compartment type..
        /// </summary>
        internal static string CompartmentDefinitionInvalidCompartmentType {
            get {
                return ResourceManager.GetString("CompartmentDefinitionInvalidCompartmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bundle.entry[{0}].resource is null or is not a CompartmentDefinition resource..
        /// </summary>
        internal static string CompartmentDefinitionInvalidResource {
            get {
                return ResourceManager.GetString("CompartmentDefinitionInvalidResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bundle.entry[{0}].resource.url is invalid..
        /// </summary>
        internal static string CompartmentDefinitionInvalidUrl {
            get {
                return ResourceManager.GetString("CompartmentDefinitionInvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bundle.entry[{0}].resource has duplicate compartment definitions..
        /// </summary>
        internal static string CompartmentDefinitionIsDupe {
            get {
                return ResourceManager.GetString("CompartmentDefinitionIsDupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartment id is null or empty..
        /// </summary>
        internal static string CompartmentIdIsInvalid {
            get {
                return ResourceManager.GetString("CompartmentIdIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartment type {0} is invalid..
        /// </summary>
        internal static string CompartmentTypeIsInvalid {
            get {
                return ResourceManager.GetString("CompartmentTypeIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The composite separator cannot be found..
        /// </summary>
        internal static string CompositeSeparatorNotFound {
            get {
                return ResourceManager.GetString("CompositeSeparatorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The _count parameter must be between {0} and {1}..
        /// </summary>
        internal static string ConditionalDeleteCountOutOfRange {
            get {
                return ResourceManager.GetString("ConditionalDeleteCountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was not attempted because search criteria was not selective enough..
        /// </summary>
        internal static string ConditionalOperationNotSelectiveEnough {
            get {
                return ResourceManager.GetString("ConditionalOperationNotSelectiveEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was stopped due to the underlying request being too resource intensive. If possible, try narrowing or changing the criteria..
        /// </summary>
        internal static string ConditionalRequestTooCostly {
            get {
                return ResourceManager.GetString("ConditionalRequestTooCostly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found result with Id &apos;{0}&apos;, which did not match the provided Id &apos;{1}&apos;..
        /// </summary>
        internal static string ConditionalUpdateMismatchedIds {
            get {
                return ResourceManager.GetString("ConditionalUpdateMismatchedIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to access the container registry &apos;{0}&apos;, please check the registry configuration..
        /// </summary>
        internal static string ContainerRegistryNotAuthorized {
            get {
                return ResourceManager.GetString("ContainerRegistryNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert the input data. Reason: {0}.
        /// </summary>
        internal static string ConvertDataFailed {
            get {
                return ResourceManager.GetString("ConvertDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert data operation has timed out..
        /// </summary>
        internal static string ConvertDataOperationTimeout {
            get {
                return ResourceManager.GetString("ConvertDataOperationTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;seealso&apos; link id cannot be null when a &apos;seealso&apos; link is being processed..
        /// </summary>
        internal static string CurrentSeeAlsoLinkIdShouldNotBeNull {
            get {
                return ResourceManager.GetString("CurrentSeeAlsoLinkIdShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prefix used to identify custom audit headers cannot be empty..
        /// </summary>
        internal static string CustomHeaderPrefixCannotBeEmpty {
            get {
                return ResourceManager.GetString("CustomHeaderPrefixCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred creating the custom search parameter.  The issue must be resolved and the parameter resubmitted to become functional..
        /// </summary>
        internal static string CustomSearchCreateError {
            get {
                return ResourceManager.GetString("CustomSearchCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred deleting the custom search parameter.  The issue must be resolved and the delete request resubmitted to remove the parameter..
        /// </summary>
        internal static string CustomSearchDeleteError {
            get {
                return ResourceManager.GetString("CustomSearchDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Search parameter with Uri: {0} was not found..
        /// </summary>
        internal static string CustomSearchParameterNotfound {
            get {
                return ResourceManager.GetString("CustomSearchParameterNotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred updating the custom search parameter.  The issue must be resolved and the update resubmitted to be applied..
        /// </summary>
        internal static string CustomSearchUpdateError {
            get {
                return ResourceManager.GetString("CustomSearchUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date time string &apos;{0}&apos; is not in a correct format..
        /// </summary>
        internal static string DateTimeStringIsIncorrectlyFormatted {
            get {
                return ResourceManager.GetString("DateTimeStringIsIncorrectlyFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one portion of the date time string &apos;{0}&apos; is out of range..
        /// </summary>
        internal static string DateTimeStringIsOutOfRange {
            get {
                return ResourceManager.GetString("DateTimeStringIsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting a specific record version is not supported..
        /// </summary>
        internal static string DeleteVersionNotAllowed {
            get {
                return ResourceManager.GetString("DeleteVersionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} roles with the name &apos;{1}&apos;.
        /// </summary>
        internal static string DuplicateRoleNames {
            get {
                return ResourceManager.GetString("DuplicateRoleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;_elements&apos; parameter is supported only when &apos;_summary&apos; is SummaryType.False or &apos;_summary&apos; is not specified at all..
        /// </summary>
        internal static string ElementsAndSummaryParametersAreIncompatible {
            get {
                return ResourceManager.GetString("ElementsAndSummaryParametersAreIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validating roles:
        ///{0}.
        /// </summary>
        internal static string ErrorValidatingRoles {
            get {
                return ResourceManager.GetString("ErrorValidatingRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient with id `{0}` is no longer relevant. Use patient with id `{1}` instead..
        /// </summary>
        internal static string EverythingOperationResourceIrrelevant {
            get {
                return ResourceManager.GetString("EverythingOperationResourceIrrelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string ExportFormatNotFound {
            get {
                return ResourceManager.GetString("ExportFormatNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to anonymize resource. The job will be marked as failed. {0}.
        /// </summary>
        internal static string FailedToAnonymizeResource {
            get {
                return ResourceManager.GetString("FailedToAnonymizeResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch the template collection. Reason: {0}.
        /// </summary>
        internal static string FetchTemplateCollectionFailed {
            get {
                return ResourceManager.GetString("FetchTemplateCollectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fhirUser claim must be a URI with an ending format of &lt;resourceType&gt;/&lt;resourceId&gt;..
        /// </summary>
        internal static string FhirUserClaimInvalidFormat {
            get {
                return ResourceManager.GetString("FhirUserClaimInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given fhirUser claim:{0} is not valid.  It must have a resource type of Patient or Practicioner and a resource id..
        /// </summary>
        internal static string FhirUserClaimMustHaveResourceTypeAndId {
            get {
                return ResourceManager.GetString("FhirUserClaimMustHaveResourceTypeAndId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization failed..
        /// </summary>
        internal static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member match encountered an unknown exception while performing the search..
        /// </summary>
        internal static string GenericMemberMatch {
            get {
                return ResourceManager.GetString("GenericMemberMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} cannot a be a value in the future..
        /// </summary>
        internal static string HistoryParameterBeforeCannotBeFuture {
            get {
                return ResourceManager.GetString("HistoryParameterBeforeCannotBeFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id must be any combination of upper or lower case ASCII letters (&apos;A&apos;..&apos;Z&apos;, and &apos;a&apos;..&apos;z&apos;), numerals (&apos;0&apos;..&apos;9&apos;), &apos;-&apos; and &apos;.&apos;, with a length limit of 64 characters. (This might be an integer, an un-prefixed OID, UUID, or any other identifier pattern that meets these constraints.).
        /// </summary>
        internal static string IdRequirements {
            get {
                return ResourceManager.GetString("IdRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid if-match header is required for resource type &apos;{0}&apos;..
        /// </summary>
        internal static string IfMatchHeaderRequiredForResource {
            get {
                return ResourceManager.GetString("IfMatchHeaderRequiredForResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal attribute name &apos;{0}&apos; on element &apos;{1}&apos;..
        /// </summary>
        internal static string IllegalHtmlAttribute {
            get {
                return ResourceManager.GetString("IllegalHtmlAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal element name &apos;{0}&apos;..
        /// </summary>
        internal static string IllegalHtmlElement {
            get {
                return ResourceManager.GetString("IllegalHtmlElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The div element must not be empty or only whitespace..
        /// </summary>
        internal static string IllegalHtmlEmpty {
            get {
                return ResourceManager.GetString("IllegalHtmlEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XHTML content should be contained within a single &lt;div&gt; element..
        /// </summary>
        internal static string IllegalHtmlOuterDiv {
            get {
                return ResourceManager.GetString("IllegalHtmlOuterDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while parsing XHTML: {0} Line: {1} Col: {2}..
        /// </summary>
        internal static string IllegalHtmlParsingError {
            get {
                return ResourceManager.GetString("IllegalHtmlParsingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an import job running..
        /// </summary>
        internal static string ImportJobIsRunning {
            get {
                return ResourceManager.GetString("ImportJobIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested import job &quot;{0}&quot; was not found..
        /// </summary>
        internal static string ImportJobNotFound {
            get {
                return ResourceManager.GetString("ImportJobNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import operation has already completed.
        /// </summary>
        internal static string ImportOperationCompleted {
            get {
                return ResourceManager.GetString("ImportOperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The _include search cannot be used against the base route..
        /// </summary>
        internal static string IncludeCannotBeAgainstBase {
            get {
                return ResourceManager.GetString("IncludeCannotBeAgainstBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0}={1} with circular reference is executed once (a single iteration)..
        /// </summary>
        internal static string IncludeIterateCircularReferenceExecutedOnce {
            get {
                return ResourceManager.GetString("IncludeIterateCircularReferenceExecutedOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The _include search is missing the type to search..
        /// </summary>
        internal static string IncludeMissingType {
            get {
                return ResourceManager.GetString("IncludeMissingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target resource type cannot be empty..
        /// </summary>
        internal static string IncludeRevIncludeInvalidTargetResourceType {
            get {
                return ResourceManager.GetString("IncludeRevIncludeInvalidTargetResourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; with value &apos;{1}&apos; is not supported..
        /// </summary>
        internal static string InvalidBooleanConfigSetting {
            get {
                return ResourceManager.GetString("InvalidBooleanConfigSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given conditional reference &apos;{0}&apos; does not resolve to a resource..
        /// </summary>
        internal static string InvalidConditionalReference {
            get {
                return ResourceManager.GetString("InvalidConditionalReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource type and query parameter must be present in a given request &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidConditionalReferenceParameters {
            get {
                return ResourceManager.GetString("InvalidConditionalReferenceParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; is not supported. Please select from the following list of supported capabilities: [{1}]..
        /// </summary>
        internal static string InvalidConfigSetting {
            get {
                return ResourceManager.GetString("InvalidConfigSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The continuation token is invalid..
        /// </summary>
        internal static string InvalidContinuationToken {
            get {
                return ResourceManager.GetString("InvalidContinuationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phase &apos;{0}&apos; in $everything operation is invalid..
        /// </summary>
        internal static string InvalidEverythingOperationPhase {
            get {
                return ResourceManager.GetString("InvalidEverythingOperationPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;handling&apos; value &apos;{0}&apos; is invalid. The supported values are: {1}..
        /// </summary>
        internal static string InvalidHandlingValue {
            get {
                return ResourceManager.GetString("InvalidHandlingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner &apos;{0}&apos; are not supported.
        /// </summary>
        internal static string InvalidInnerUnionExpression {
            get {
                return ResourceManager.GetString("InvalidInnerUnionExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reindex operation parameter &apos;{0}&apos; was out of the range of valid values. Please specify different value within a range &apos;{1}&apos; - &apos;{2}&apos;..
        /// </summary>
        internal static string InvalidReIndexParameterValue {
            get {
                return ResourceManager.GetString("InvalidReIndexParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The count must be greater than zero..
        /// </summary>
        internal static string InvalidSearchCountSpecified {
            get {
                return ResourceManager.GetString("InvalidSearchCountSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Security configuration base endpoint {0} is an invalid Uri&quot;..
        /// </summary>
        internal static string InvalidSecurityConfigurationBaseEndpoint {
            get {
                return ResourceManager.GetString("InvalidSecurityConfigurationBaseEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;_total&apos; parameter value &apos;{0}&apos; is invalid. The supported values are: {1}..
        /// </summary>
        internal static string InvalidTotalParameter {
            get {
                return ResourceManager.GetString("InvalidTotalParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;_type&apos; parameter contains unknown resource(s): {0}.
        /// </summary>
        internal static string InvalidTypeParameter {
            get {
                return ResourceManager.GetString("InvalidTypeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for :missing modifier. Valid values are: true, false..
        /// </summary>
        internal static string InvalidValueTypeForMissingModifier {
            get {
                return ResourceManager.GetString("InvalidValueTypeForMissingModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested job &quot;{0}&quot; was not found..
        /// </summary>
        internal static string JobNotFound {
            get {
                return ResourceManager.GetString("JobNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle.link values omitted because they exceeded the maximum Uri length..
        /// </summary>
        internal static string LinksCantBeCreated {
            get {
                return ResourceManager.GetString("LinksCantBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed search value &apos;{0}&apos;..
        /// </summary>
        internal static string MalformedSearchValue {
            get {
                return ResourceManager.GetString("MalformedSearchValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found multiple matches, narrow search criteria..
        /// </summary>
        internal static string MemberMatchMultipleMatchesFound {
            get {
                return ResourceManager.GetString("MemberMatchMultipleMatchesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match found..
        /// </summary>
        internal static string MemberMatchNoMatchFound {
            get {
                return ResourceManager.GetString("MemberMatchNoMatchFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta.
        /// </summary>
        internal static string Meta {
            get {
                return ResourceManager.GetString("Meta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier &apos;{0}&apos; is not supported for search parameter &apos;{1}&apos;..
        /// </summary>
        internal static string ModifierNotSupported {
            get {
                return ResourceManager.GetString("ModifierNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one token separator can be specified..
        /// </summary>
        internal static string MoreThanOneTokenSeparatorSpecified {
            get {
                return ResourceManager.GetString("MoreThanOneTokenSeparatorSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more than two token separators can be specified..
        /// </summary>
        internal static string MoreThanTwoTokenSeparatorSpecified {
            get {
                return ResourceManager.GetString("MoreThanTwoTokenSeparatorSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query parameter &apos;{0}&apos; cannot be specified more than once..
        /// </summary>
        internal static string MultipleQueryParametersNotAllowed {
            get {
                return ResourceManager.GetString("MultipleQueryParametersNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple sort parameters are currently not supported. Only a single sort parameter is supported..
        /// </summary>
        internal static string MultiSortParameterNotSupported {
            get {
                return ResourceManager.GetString("MultiSortParameterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No resources were found matching the type of the updated search parameters needing to be reindexed.  ReindexJob marked completed..
        /// </summary>
        internal static string NoResourcesNeedToBeReindexed {
            get {
                return ResourceManager.GetString("NoResourcesNeedToBeReindexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search parameters found needing to be indexed.  Job cancelled..
        /// </summary>
        internal static string NoSearchParametersNeededToBeIndexed {
            get {
                return ResourceManager.GetString("NoSearchParametersNeededToBeIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of composite components specified for search parameter &apos;{0}&apos; exceeded the number of components defined..
        /// </summary>
        internal static string NumberOfCompositeComponentsExceeded {
            get {
                return ResourceManager.GetString("NumberOfCompositeComponentsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only equal comparator is supported for this search type..
        /// </summary>
        internal static string OnlyEqualComparatorIsSupported {
            get {
                return ResourceManager.GetString("OnlyEqualComparatorIsSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one modifier separator can be specified..
        /// </summary>
        internal static string OnlyOneModifierSeparatorSupported {
            get {
                return ResourceManager.GetString("OnlyOneModifierSeparatorSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one active or paused reindex job allowed.  Cancel job with id: {0} before submitting a new job..
        /// </summary>
        internal static string OnlyOneResourceJobAllowed {
            get {
                return ResourceManager.GetString("OnlyOneResourceJobAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the OpenId configuration from the authentication provider..
        /// </summary>
        internal static string OpenIdConfiguration {
            get {
                return ResourceManager.GetString("OpenIdConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attempted operation was cancelled, please retry the request. If you believe you have received this message in error, please contact Customer Support..
        /// </summary>
        internal static string OperationCanceled {
            get {
                return ResourceManager.GetString("OperationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} operation failed for reason: {1}.
        /// </summary>
        internal static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationOutcome.Location is deprecated, please use OperationOutcome.Expression.
        /// </summary>
        internal static string OperationOutcomeLocationDeprication {
            get {
                return ResourceManager.GetString("OperationOutcomeLocationDeprication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  or .
        /// </summary>
        internal static string OrDelimiter {
            get {
                return ResourceManager.GetString("OrDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching immutable properties is not allowed..
        /// </summary>
        internal static string PatchImmutablePropertiesIsNotValid {
            get {
                return ResourceManager.GetString("PatchImmutablePropertiesIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error patching resource: &apos;{0}&apos;..
        /// </summary>
        internal static string PatchResourceError {
            get {
                return ResourceManager.GetString("PatchResourceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource to patch must be in JSON format..
        /// </summary>
        internal static string PatchResourceMustBeJson {
            get {
                return ResourceManager.GetString("PatchResourceMustBeJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching a specific record version is not supported..
        /// </summary>
        internal static string PatchVersionNotAllowed {
            get {
                return ResourceManager.GetString("PatchVersionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Provenance header is malformed and can&apos;t be parsed.
        /// </summary>
        internal static string ProvenanceHeaderMalformed {
            get {
                return ResourceManager.GetString("ProvenanceHeaderMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Provenance header shall not have a specified `Provenance.target`.
        /// </summary>
        internal static string ProvenanceHeaderShouldntHaveTarget {
            get {
                return ResourceManager.GetString("ProvenanceHeaderShouldntHaveTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadHistory is disabled for resources of type &apos;{0}&apos;..
        /// </summary>
        internal static string ReadHistoryDisabled {
            get {
                return ResourceManager.GetString("ReadHistoryDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource type &apos;{0}&apos; in the reference &apos;{1}&apos; is not supported..
        /// </summary>
        internal static string ReferenceResourceTypeNotSupported {
            get {
                return ResourceManager.GetString("ReferenceResourceTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more resources to be reindexed were not found, indicating that they have been deleted since the reindex job kicked off..
        /// </summary>
        internal static string ReindexingResourceNotFound {
            get {
                return ResourceManager.GetString("ReindexingResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more resources failed to reindex due to a non-matching version..
        /// </summary>
        internal static string ReindexingResourceVersionConflict {
            get {
                return ResourceManager.GetString("ReindexingResourceVersionConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} resource(s) failed to reindex due to a non-matching version..
        /// </summary>
        internal static string ReindexingResourceVersionConflictWithCount {
            get {
                return ResourceManager.GetString("ReindexingResourceVersionConflictWithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resubmit the same reindex job to finish indexing the remaining resources..
        /// </summary>
        internal static string ReindexingUserAction {
            get {
                return ResourceManager.GetString("ReindexingUserAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reindex job id {0} is in state {1} and cannot be cancelled..
        /// </summary>
        internal static string ReindexJobInCompletedState {
            get {
                return ResourceManager.GetString("ReindexJobInCompletedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested action is not allowed..
        /// </summary>
        internal static string RequestedActionNotAllowed {
            get {
                return ResourceManager.GetString("RequestedActionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timespan in export request contains too much data to export in a single request. Please try reducing the time range and try again..
        /// </summary>
        internal static string RequestEntityTooLargeExceptionDuringExport {
            get {
                return ResourceManager.GetString("RequestEntityTooLargeExceptionDuringExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource creation is not allowed..
        /// </summary>
        internal static string ResourceCreationNotAllowed {
            get {
                return ResourceManager.GetString("ResourceCreationNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource type &apos;{0}&apos; with id &apos;{1}&apos; couldn&apos;t be found..
        /// </summary>
        internal static string ResourceNotFoundById {
            get {
                return ResourceManager.GetString("ResourceNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource type &apos;{0}&apos; with id &apos;{1}&apos; and version &apos;{2}&apos; couldn&apos;t be found..
        /// </summary>
        internal static string ResourceNotFoundByIdAndVersion {
            get {
                return ResourceManager.GetString("ResourceNotFoundByIdAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string ResourceNotSupported {
            get {
                return ResourceManager.GetString("ResourceNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource exceeded the backing database&apos;s size limit..
        /// </summary>
        internal static string ResourceTooLarge {
            get {
                return ResourceManager.GetString("ResourceTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource type {0} is not allowed. Additional clinical scopes should be requested to allow searching using this type..
        /// </summary>
        internal static string ResourceTypeNotAllowedRestrictedByClinicalScopes {
            get {
                return ResourceManager.GetString("ResourceTypeNotAllowedRestrictedByClinicalScopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied version &apos;{0}&apos; did not match..
        /// </summary>
        internal static string ResourceVersionConflict {
            get {
                return ResourceManager.GetString("ResourceVersionConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reverse chain search is missing the reference to search..
        /// </summary>
        internal static string ReverseChainMissingReference {
            get {
                return ResourceManager.GetString("ReverseChainMissingReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reverse chain search is missing the type to search..
        /// </summary>
        internal static string ReverseChainMissingType {
            get {
                return ResourceManager.GetString("ReverseChainMissingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;_revinclude:iterate={0}&apos; search parameter has multiple target types. Please specify a target type..
        /// </summary>
        internal static string RevIncludeIterateTargetTypeNotSpecified {
            get {
                return ResourceManager.GetString("RevIncludeIterateTargetTypeNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The _revinclude search is missing the type to search..
        /// </summary>
        internal static string RevIncludeMissingType {
            get {
                return ResourceManager.GetString("RevIncludeMissingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparator is not supported when multiple values are specified using OR search parameter..
        /// </summary>
        internal static string SearchComparatorNotSupported {
            get {
                return ResourceManager.GetString("SearchComparatorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search count returned {0} and exceeds the maximum defined limit of {1}..
        /// </summary>
        internal static string SearchCountResultsExceedLimit {
            get {
                return ResourceManager.GetString("SearchCountResultsExceedLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;_count&apos; parameter exceeds limit configured for server. Current limit is {0} while `_count` parameter set to {1}..
        /// </summary>
        internal static string SearchParamaterCountExceedLimit {
            get {
                return ResourceManager.GetString("SearchParamaterCountExceedLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search parameter with definition URL &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string SearchParameterByDefinitionUriNotSupported {
            get {
                return ResourceManager.GetString("SearchParameterByDefinitionUriNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchParameter[{0}].resource.base is not defined..
        /// </summary>
        internal static string SearchParameterDefinitionBaseNotDefined {
            get {
                return ResourceManager.GetString("SearchParameterDefinitionBaseNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchParameter[{0}].component[{1}] cannot refer to a composite SearchParameter..
        /// </summary>
        internal static string SearchParameterDefinitionComponentReferenceCannotBeComposite {
            get {
                return ResourceManager.GetString("SearchParameterDefinitionComponentReferenceCannotBeComposite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A search parameter with the same code value &apos;{0}&apos; already exists for base type &apos;{1}&apos;..
        /// </summary>
        internal static string SearchParameterDefinitionConflictingCodeValue {
            get {
                return ResourceManager.GetString("SearchParameterDefinitionConflictingCodeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search parameter definition contains one or more invalid entries..
        /// </summary>
        internal static string SearchParameterDefinitionContainsInvalidEntry {
            get {
                return ResourceManager.GetString("SearchParameterDefinitionContainsInvalidEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A search parameter with the same definition URL &apos;{0}&apos; already exists..
        /// </summary>
        internal static string SearchParameterDefinitionDuplicatedEntry {
            get {
                return ResourceManager.GetString("SearchParameterDefinitionDuplicatedEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchParameter[{0}].component is null or empty..
        /// </summary>
        internal static string SearchParameterDefinitionInvalidComponent {
            get {
                return ResourceManager.GetString("SearchParameterDefinitionInvalidComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchParameter[{0}].component[{1}].expression is null or empty..
        /// </summary>
        internal static string SearchParameterDefinitionInvalidComponentExpression {
            get {
                return ResourceManager.GetString("SearchParameterDefinitionInvalidComponentExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchParameter[{0}].component[{1}].definition.reference is null or empty or does not refer to a valid SearchParameter resource..
        /// </summary>
        internal static string SearchParameterDefinitionInvalidComponentReference {
            get {
                return ResourceManager.GetString("SearchParameterDefinitionInvalidComponentReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchParameter[{0}].url is invalid..
        /// </summary>
        internal static string SearchParameterDefinitionInvalidDefinitionUri {
            get {
                return ResourceManager.GetString("SearchParameterDefinitionInvalidDefinitionUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchParameter[{0}].resource.expression is null or empty..
        /// </summary>
        internal static string SearchParameterDefinitionInvalidExpression {
            get {
                return ResourceManager.GetString("SearchParameterDefinitionInvalidExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search parameter defintion is missing the Uri..
        /// </summary>
        internal static string SearchParameterDefinitionInvalidMissingUri {
            get {
                return ResourceManager.GetString("SearchParameterDefinitionInvalidMissingUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry {0} is not a SearchParameter resource..
        /// </summary>
        internal static string SearchParameterDefinitionInvalidResource {
            get {
                return ResourceManager.GetString("SearchParameterDefinitionInvalidResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A search parameter with Uri &apos;{0}&apos; was not found..
        /// </summary>
        internal static string SearchParameterDefinitionNotFound {
            get {
                return ResourceManager.GetString("SearchParameterDefinitionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code value cannot be null or empty.
        /// </summary>
        internal static string SearchParameterDefinitionNullorEmptyCodeValue {
            get {
                return ResourceManager.GetString("SearchParameterDefinitionNullorEmptyCodeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search parameter &apos;{0}&apos; is not common for &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        internal static string SearchParameterMustBeCommon {
            get {
                return ResourceManager.GetString("SearchParameterMustBeCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} So it cannot be marked enabled..
        /// </summary>
        internal static string SearchParameterNoLongerSupported {
            get {
                return ResourceManager.GetString("SearchParameterNoLongerSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search parameter &apos;{0}&apos; is not supported for resource type &apos;{1}&apos;..
        /// </summary>
        internal static string SearchParameterNotSupported {
            get {
                return ResourceManager.GetString("SearchParameterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A search parameter is no longer supported..
        /// </summary>
        internal static string SearchParameterUnknownNotSupported {
            get {
                return ResourceManager.GetString("SearchParameterUnknownNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting by the &apos;{0}&apos; parameter is not supported..
        /// </summary>
        internal static string SearchSortParameterNotSupported {
            get {
                return ResourceManager.GetString("SearchSortParameterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security configuration authorization is not enabled..
        /// </summary>
        internal static string SecurityConfigurationAuthorizationNotEnabled {
            get {
                return ResourceManager.GetString("SecurityConfigurationAuthorizationNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FHIR Server for Azure.
        /// </summary>
        internal static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The _sort parameter is not supported..
        /// </summary>
        internal static string SortNotSupported {
            get {
                return ResourceManager.GetString("SortNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort parameter value &apos;{0}&apos; is invalid, must be a subset of valid search parameters for resource type &apos;{1}&apos;..
        /// </summary>
        internal static string SortParameterValueIsNotValidSearchParameter {
            get {
                return ResourceManager.GetString("SortParameterValueIsNotValidSearchParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query processor ran out of internal resources and could not produce a query plan. Please limit your parameters and retry..
        /// </summary>
        internal static string SqlQueryProcessorRanOutOfInternalResourcesException {
            get {
                return ResourceManager.GetString("SqlQueryProcessorRanOutOfInternalResourcesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include result was truncated.
        /// </summary>
        internal static string TruncatedIncludeMessage {
            get {
                return ResourceManager.GetString("TruncatedIncludeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The _typeFilter segment &apos;{0}&apos; could not be parsed..
        /// </summary>
        internal static string TypeFilterUnparseable {
            get {
                return ResourceManager.GetString("TypeFilterUnparseable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The _type parameter must be included when using the _typeFilter parameter..
        /// </summary>
        internal static string TypeFilterWithoutTypeIsUnsupported {
            get {
                return ResourceManager.GetString("TypeFilterWithoutTypeIsUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle type is not present. Possible values are: transaction or batch.
        /// </summary>
        internal static string TypeNotPresent {
            get {
                return ResourceManager.GetString("TypeNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete secret from SecretStore.
        /// </summary>
        internal static string UnableToDeleteSecret {
            get {
                return ResourceManager.GetString("UnableToDeleteSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get secret from SecretStore.
        /// </summary>
        internal static string UnableToGetSecret {
            get {
                return ResourceManager.GetString("UnableToGetSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set secret in SecretStore.
        /// </summary>
        internal static string UnableToSetSecret {
            get {
                return ResourceManager.GetString("UnableToSetSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to update SearchParameter {0} failed..
        /// </summary>
        internal static string UnableToUpdateSearchParameter {
            get {
                return ResourceManager.GetString("UnableToUpdateSearchParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported configuration found..
        /// </summary>
        internal static string UnsupportedConfigurationMessage {
            get {
                return ResourceManager.GetString("UnsupportedConfigurationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;_total&apos; parameter value &apos;{0}&apos; is not supported. The supported values are: {1}..
        /// </summary>
        internal static string UnsupportedTotalParameter {
            get {
                return ResourceManager.GetString("UnsupportedTotalParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource id is required for updates..
        /// </summary>
        internal static string UpdateRequestsRequireId {
            get {
                return ResourceManager.GetString("UpdateRequestsRequireId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User requested cancellation of operation..
        /// </summary>
        internal static string UserRequestedCancellation {
            get {
                return ResourceManager.GetString("UserRequestedCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All OK.
        /// </summary>
        internal static string ValidationPassed {
            get {
                return ResourceManager.GetString("ValidationPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null.  Parameter name: {0}..
        /// </summary>
        internal static string ValueCannotBeNull {
            get {
                return ResourceManager.GetString("ValueCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VersionId should not be in the weak ETag format..
        /// </summary>
        internal static string VersionIdFormatNotETag {
            get {
                return ResourceManager.GetString("VersionIdFormatNotETag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeakETag &apos;{0}&apos; must be in the weak ETag format..
        /// </summary>
        internal static string WeakETagFormatRequired {
            get {
                return ResourceManager.GetString("WeakETagFormatRequired", resourceCulture);
            }
        }
    }
}
