<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Microsoft.Health.Internal.Fhir.IncludePerf.DataGenerator</AssemblyName>
    <RootNamespace>Microsoft.Health.Internal.Fhir.IncludePerf.DataGenerator</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
