
@fhirurl= https://localhost:44348

@contentType = application/json

GET {{fhirurl}}/metadata
content-type: {{contentType}}

###
GET  {{fhirurl}}/$export?_isParallel=true
content-type: {{contentType}}
Accept: application/fhir+json
Prefer: respond-async

###
GET https://localhost:44348/_operations/export/5109418223003200676