-- Enable RCSI
ALTER DATABASE CURRENT SET READ_COMMITTED_SNAPSHOT ON;

-- Create Resource table
IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Resources' )
BEGIN
    CREATE TABLE Resources (ResourceId int PRIMARY KEY);
END
